### ISSUE TITLE
LauraTTS的GPT没有任何优化吗? 直接用的torch.matmul?

### ISSUE THREAD

**Issue by MinJ-lucky** [alibaba-damo-academy/FunCodec#16]
如题... 这样batchsize能撑起来吗?

**Comment by ZhihaoDU** [comment]
Sorry, I can't understand your question, please provide more details to specify the question, thanks.

**Comment by MinJ-lucky** [comment]
My bad, let me explain my question.
As far as I know, big GPT-like models always use some optimization in attention like FlashAttention for less GPU mem cost and improve the forward speed. However, I didn't find any like this, only find a "torch.matmul" at [here](https://github.com/alibaba-damo-academy/FunCodec/blob/master/funcodec/modules/attention.py#L113). I'd like to make sure that I'm correct, or there is optimization somewhere else~

**Comment by ZhihaoDU** [comment]
Yes, you are correct. In FunCodec and LauraTTS, we didn't include any optimization on attention operation, since the model is very small.

**Comment by MinJ-lucky** [comment]
Thanks for your reply! 
After reading the code, I still have two little questions: 
1. Is LauraTTS a totally independent model, which is trained from scratch without any pretrained parameters from LauraGPT? 
2.Since I see LauraGPT paper is also referenced in this repo, also taking into consideration that LauraGPT and LauraTTS has highly similar name, what's the relevance between both?

**Comment by ZhihaoDU** [comment]
1. Yes, LauraTTS is a totally independent model, you can train it from scratch on LibriTTS corpus with the released code.
2. The reason of LauraGPT paper referencing this repo is because LauraGPT use the same codec model to tokenize speech signals. In fact, LauraTTS can be treated as a improved version of LauraGPT for TTS task only. There are two main differences between LauraTTS and LauraGPT in terms of TTS task: 1) LauraTTS use two codec groups in LM model rather than one. 2) In LauraTTS the LM and NAR model are jointly trained while they are trained separately in LauraGPT.

**Comment by ZhihaoDU** [comment]
> Thanks for your reply! After reading the code, I still have two little questions:
> 
> 1. Is LauraTTS a totally independent model, which is trained from scratch without any pretrained parameters from LauraGPT?
>    2.Since I see LauraGPT paper is also referenced in this repo, also taking into consideration that LauraGPT and LauraTTS has highly similar name, what's the relevance between both?

1. Yes, LauraTTS is a totally independent model, you can train it from scratch on LibriTTS corpus with the released code.
2. The reason of LauraGPT paper referencing this repo is because LauraGPT use the same codec model to tokenize speech signals. In fact, LauraTTS can be treated as a improved version of LauraGPT for TTS task only. There are two main differences between LauraTTS and LauraGPT in terms of TTS task: 1) LauraTTS use two codec groups in LM model rather than one. 2) In LauraTTS the LM and NAR model are jointly trained while they are trained separately in LauraGPT.
