### ISSUE TITLE
如何仅用funcodec的4层或者8层量化器进行推理

### ISSUE THREAD

**Issue by jishengpeng** [alibaba-damo-academy/FunCodec#37]
您好，我想测试一下funcodec在4层或者8层codec下的性能，我尝试将配置文件中超参直接设置为8，但是这样修改后他仅仅会生成一层的codec。我又尝试在推理阶段的ddp_core_vq.py文件中，强制将32层codec的后24层设置为0，但是这样推理出来的音频重建效果很差，请问正确处理方式应该怎样呢

**Comment by ZhihaoDU** [comment]
You can use the `bit_width` option in `egs/LibriTTS/codec/encoding_decoding.sh`. Note that, this option depends on the model you use. 
For example, if you want test the performance of using 4 RVQ layers with the `ds640` models, you should set the `bit_width` to 1000 (TKR=100). For 4 RVQ layers with ds320 models, you should set it to 2000 (TKR=200), since the token rate becomes 50 per RVQ layer and per second.
The calculation method of `bit_width` can be found at https://github.com/alibaba-damo-academy/FunCodec/issues/27

**Comment by jishengpeng** [comment]
明白了，非常感谢您的解答，祝您周末愉快
