### ISSUE TITLE
The effect of this model is amazing, is there any performance in music?

### ISSUE THREAD

**Issue by 980202006** [alibaba-damo-academy/FunCodec#4]
The effect of this model is amazing, is there any performance in music?

**Comment by ZhihaoDU** [comment]
Good question! Currently, We are making effort on developing music codec models. If you know any open-source music datasets, please let me know, boosting up the development.
I have evaluated the general-purpose model `audio_codec-encodec-zh_en-general-16k-nq32ds640-pytorch` on Jamendo and LP-Music-MSD datasets. But, the performance is a little poor, which achieves `2.99~3.19` and `3.54~3.76` ViSQOL score under 1k and 8k bit-rate, respectively. This is because this model is only trained with speech data only.

**Comment by 980202006** [comment]
Thanks Reply. MusicCaps, Million Song Dataset Subset, these are the ones I know. Looking forward to the release of your musical models.
